version: '3.8'

services:

  lndc-backend:
    container_name: lndc-backend-container
    build:
      context: ./
      dockerfile: Dockerfile
    image: lndc-backend:latest
    ports:
      - 8090:8080

  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"  # Running on 5433 to avoid conflicts with local PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
